### PR TITLE
Add support for https includes -- Review: Infinite inclusions

### PR DESCRIPTION
**Pull request by lucafavatellawork**
TODO:
- [ ] Understand `test_self_include` (self including) test behaviour.
- [ ] Consider whether to include test of A and B mutually including.
- [ ] Consider whether to include test of programmatic HTTP server serving never ending chain of distinct URLs.

### CODE REVIEW

**Comment by lucafavatellawork** [comment]
I observe this failure:
```
=== Location: [{includes_SUITE,import_on_node,195},
              {includes_SUITE,test_self_include,167},
              {test_server,ts_tc,1754},
              {test_server,run_test_case_eval1,1263},
              {test_server,run_test_case_eval,1195}]
=== === Reason: no match of right hand side value {error,
                                                    {xslt_error,
                                                     [{cmd,
                                                       "/usr/bin/xsltproc -o /tmp/sse62749875.tmp  --stringparam cwd '/Users/.../dev/pid/sse_core/apps/sse_cfg/.build/ct_logs/ct_run.ct@127.0.0.1.2020-02-12_17.32.59/.build.ct_objs.includes_SUITE.logs/run.2020-02-12_17.32.59/log_private.7/nodes/sse1' --stringparam baseuri 'http://localhost:8000/self_including_content.xml' /Users/.../dev/pid/sse_core/apps/sse_cfg/priv/gen_change.xsl /tmp/sse111872817.tmp"},
                                                      {status,6},
                                                      {output,
                                                       "/tmp/sse111872817.tmp:24: parser error : Extra content at the end of the document\n<include href=\"http://localhost:8000/self_including_content.xml\"/>\n^\nunable to parse /tmp/sse111872817.tmp\n"}]}}
  in function  includes_SUITE:import_on_node/3 (ct_test/includes_SUITE.erl, line 195)
  in call from includes_SUITE:test_self_include/1 (ct_test/includes_SUITE.erl, line 167)
  in call from test_server:ts_tc/3 (test_server.erl, line 1754)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1263)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1195)
```

Content of `sse111872817.tmp`:
```
<?xml version="1.0"?>
<change>
  <folder base="http://localhost:8000/self_including_content.xml" name="included_content"/>
  <enter name="included_content"/>
  <service name="Expr" provision="expr">
    <prop name="expr.src" href="PropSrc.txt" type="application/x-erlang"/>
  </service>
  <field name="input" type="string"/>
  <field name="output" type="string"/>
  <mix name="Mix"/>
  <enter name="Mix"/>
  <request name="See" service="Expr" fields="input">
    <prop name="expr.src">
				In = get("input"),
				put("output", GetHello(In)),
				"Ok".
			</prop>
    <reply name="Ok" fields="output"/>
  </request>
  <exit/>
  <include href="http://localhost:8000/self_including_content.xml"/>
  <exit/>
</change>
<include href="http://localhost:8000/self_including_content.xml"/>
```

**Comment by lucafavatellawork** [comment]
Still for `test_self_include`: I see approx. 46 HTTP GET requests for `/self_including_content.xml`, not sure why it then stops recursion.

On a partially unrelated note: I observed failure for spurious trailing `<include href="http://localhost:8000/included_content.xml"/>` line once locally also for `test_include_proxy_2` so I suspect that the trailing line for `test_self_include` may be a red herring made more deterministic by the slower recursive inclusion.

**Comment by lucafavatellawork** [comment]
Suggested approach for running tests - after `make deps compile` once:
```
make clean_ct; pkill -9 ct_run; pkill -9 beam; env SUITES=includes make -C apps/sse_cfg ct; make -C apps/sse_cfg view_ct
```

**Comment by lucafavatellawork** [comment]
```
=== Location: [{includes_SUITE,import_on_node,195},
              {includes_SUITE,test_self_include,167},
              {test_server,ts_tc,1754},
              {test_server,run_test_case_eval1,1263},
              {test_server,run_test_case_eval,1195}]
=== === Reason: no match of right hand side value {error,
                                                    {xslt_error,
                                                     [{cmd,
                                                       "/usr/bin/xsltproc -o /tmp/sse93094169.tmp  --stringparam cwd '/Users/.../dev/pid/sse_core/apps/sse_cfg/.build/ct_logs/ct_run.ct@127.0.0.1.2020-02-12_18.19.39/.build.ct_objs.includes_SUITE.logs/run.2020-02-12_18.19.39/log_private.7/nodes/sse1' --stringparam baseuri 'http://localhost:8000/self_including_content.xml' /Users/.../dev/pid/sse_core/apps/sse_cfg/priv/gen_change.xsl /tmp/sse83676894.tmp"},
                                                      {status,6},
                                                      {output,
                                                       "/tmp/sse83676894.tmp:4: parser error : Extra content at the end of the document\n<include href=\"http://localhost:8000/self_including_content.xml\"/>\n^\nunable to parse /tmp/sse83676894.tmp\n"}]}}
  in function  includes_SUITE:import_on_node/3 (ct_test/includes_SUITE.erl, line 195)
  in call from includes_SUITE:test_self_include/1 (ct_test/includes_SUITE.erl, line 167)
  in call from test_server:ts_tc/3 (test_server.erl, line 1754)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1263)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1195)
```

Temporary file:
```
<folder name="self_including_content">
	<include href="http://localhost:8000/self_including_content.xml"/>
</folder>
<include href="http://localhost:8000/self_including_content.xml"/>
```

**Comment by lucafavatellawork** [comment]
Rebased on current `doc_uri-review-test-deep-includes`.

**Comment by lucafavatellawork** [comment]
Rebased on current base branch.

**Comment by jacobythwaites** [comment]
I've cherrypicked the commit from this PR into #96 which addresses circular references and too-deep include chains.

**Comment by lucafavatellawork** [comment]
See #96

**Pull request closed without merging**
